In [318]:
import numpy as np

Чистая сеть с несколькими выходами

In [319]:
def w_sum(a, b):
    
    assert(len(a) == len(b))
    
    output = 0
    
    for i in range(len(a)):
        output += (a[i] * b[i])
        
    return output
        

In [320]:
weights = [0.1, 0.2, -.1]

In [321]:
def neural_network(input, weights):
    
    pred = w_sum(input, weights)
    
    return pred

Получение прогноза, вычисление ошибки и разности

In [322]:
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

win_or_lose_binary = [1, 1, 0, 1]

true = win_or_lose_binary[0]
input = [toes[0], wlrec[0], nfans[0]]

pred = neural_network(input, weights)

error = (pred - true) ** 2

delta = pred - true

In [323]:
print(np.round(pred, 4))
print(np.round(error, 4))
print(np.round(delta, 4))

0.86
0.0196
-0.14


Вычисление всех операций и добавление их в каждый вес

In [324]:
def ele_mul(number, vector):
    
    output = [0, 0, 0]
    
    assert(len(output) == len(vector))
    
    for i in range(len(vector)):
        output[i] = number * vector[i]
        
    return output

In [325]:
weights_delta = ele_mul(delta, input)

In [326]:
print(weights_delta[0], weights_delta[1], weights_delta[2])

-1.189999999999999 -0.09099999999999994 -0.16799999999999987


Корректировка весов

In [327]:
alpha = 0.01

In [328]:
for i in range(len(weights)):
    
    weights[i] -= alpha * weights_delta[i]
    
print('Weights :' + str(weights))
print('Weights Deltas :' + str(weights_delta))
    
    

Weights :[0.1119, 0.20091, -0.09832]
Weights Deltas :[-1.189999999999999, -0.09099999999999994, -0.16799999999999987]


Несколько входов: получение прогноза и вычисление ошибки и разности

In [329]:
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

win_or_lose_binary = [1, 1, 0, 1]

true = win_or_lose_binary[0]
input = [toes[0], wlrec[0], nfans[0]]

pred = neural_network(input, weights)

error = (pred - true) ** 2

delta = pred - true

In [330]:
print(np.round(pred, 4))
print(np.round(error, 4))
print(np.round(delta, 4))

0.9638
0.0013
-0.0362


Корректеровка весов

In [331]:
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0], wlrec[0], nfans[0]]

pred = neural_network(input, weights)

error =  (pred - true) ** 2
delta = pred - true

weights_delta = ele_mul(delta, input)
print(weights_delta)
alpha = 0.01

for i in range(len(weights_delta)):
    weights[i] -= alpha * weights_delta[i]
    print(weights[i])

[-0.30806125000000056, -0.023557625000000044, -0.04349100000000008]
0.11498061250000001
0.20114557625
-0.09788509000000001


Все вместе

In [332]:
def neural_network(input, weights):
    
    out = 0
    
    for i in range(len(input)):
        out += (input[i] * weights[i])
        
    return out

def ele_mul(scalar, vector):
    
    out = [0, 0, 0]
    
    for i in range(len(vector)):
        out[i] = scalar * vector[i]
        
    return out

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

win_or_lose_binary = [1, 1, 0, 1]
true = win_or_lose_binary[0]

alpha = 0.01
weights = [0.1, 0.2, -.1]
input = [toes[0], wlrec[0], nfans[0]]

for iter in range(3):
    
    pred = neural_network(input, weights)
    error = (pred - true) ** 2
    delta = pred - true
    
    weights_delta = ele_mul(delta, input)
    
    print('Iteration : ' + str(iter+1))
    print('Pred : ' + str(pred))
    print('Error : ' + str(error))
    print('Delta : ' + str(delta))
    print('Weight : ' + str(weights))
    print('Weights_delta :')
    print(str(weights_delta))
    print()
    
    for i in range(len(weights)):
        weights[i] -= alpha * weights_delta[i]

Iteration : 1
Pred : 0.8600000000000001
Error : 0.01959999999999997
Delta : -0.1399999999999999
Weight : [0.1, 0.2, -0.1]
Weights_delta :
[-1.189999999999999, -0.09099999999999994, -0.16799999999999987]

Iteration : 2
Pred : 0.9637574999999999
Error : 0.0013135188062500048
Delta : -0.036242500000000066
Weight : [0.1119, 0.20091, -0.09832]
Weights_delta :
[-0.30806125000000056, -0.023557625000000044, -0.04349100000000008]

Iteration : 3
Pred : 0.9906177228125002
Error : 8.802712522307997e-05
Delta : -0.009382277187499843
Weight : [0.11498061250000001, 0.20114557625, -0.09788509000000001]
Weights_delta :
[-0.07974935609374867, -0.006098480171874899, -0.011258732624999811]



Замораживание одного веса

In [333]:
def neural_network(input, weights):
    
    out = 0
    
    for i in range(len(input)):
        out += (input[i] * weights[i])
        
    return out

def ele_mul(scalar, vector):
    
    out = [0, 0, 0]
    
    for i in range(len(vector)):
        out[i] = scalar * vector[i]
        
    return out

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

win_or_lose_binary = [1, 1, 0, 1]
true = win_or_lose_binary[0]

alpha = 0.3
weights = [0.1, 0.2, -.1]
input = [toes[0], wlrec[0], nfans[0]]

for iter in range(3):
    
    pred = neural_network(input, weights)
    error = (pred - true) ** 2
    delta = pred - true
    
    weights_delta = ele_mul(delta, input)
    weights_delta[0] = 0
    
    print('Iteration : ' + str(iter+1))
    print('Pred : ' + str(pred))
    print('Error : ' + str(error))
    print('Delta : ' + str(delta))
    print('Weight : ' + str(weights))
    print('Weights_delta :')
    print(str(weights_delta))
    print()
    
    for i in range(len(weights)):
        weights[i] -= alpha * weights_delta[i]

Iteration : 1
Pred : 0.8600000000000001
Error : 0.01959999999999997
Delta : -0.1399999999999999
Weight : [0.1, 0.2, -0.1]
Weights_delta :
[0, -0.09099999999999994, -0.16799999999999987]

Iteration : 2
Pred : 0.9382250000000001
Error : 0.003816150624999989
Delta : -0.06177499999999991
Weight : [0.1, 0.2273, -0.04960000000000005]
Weights_delta :
[0, -0.040153749999999946, -0.07412999999999989]

Iteration : 3
Pred : 0.97274178125
Error : 0.000743010489422852
Delta : -0.027258218750000007
Weight : [0.1, 0.239346125, -0.02736100000000008]
Weights_delta :
[0, -0.017717842187500006, -0.032709862500000006]



Чистая сеть с несколькими выходами

In [334]:
weights = [0.3, 0.2, 0.9]

def neural_network(input, weights):
    
    pred = ele_mul(input, weights)
    
    return pred

In [335]:
wlrec = [0.65, 1.0, 1.0, 0.9]

hurt = [0.1, 0.0, 0.0, 0.1]
win = [1, 1, 0, 1]
sad = [0.1, 0.0, 0.1, 0.2]

input = wlrec[0]
true = [hurt[0], win[0], sad[0]]

pred = neural_network(input, weights)

error = [0, 0, 0]
delta = [0, 0, 0]

for i in range(len(pred)):
    
    error[i] = (pred[i] - true[i]) ** 2
    delta[i] = pred[i] - true[i]

Вычисление каждого приращения weight_delta и коррекция каждого веса

In [336]:
def scalar_ele_mul(number, vector):
    
    output = [0, 0, 0]
    
    assert(len(output) == len(vector))
    
    for i in range(len(vector)):
        output[i] = number * vector[i]
        
        return output

In [337]:
weights_deltas = scalar_ele_mul(input, weights)

In [338]:
weights_delta

[0, -0.017717842187500006, -0.032709862500000006]

Корректировка весов

In [339]:
alpha = 0.1

for i in range(len(weights)):
    
    weights[i] -= (alpha * weights_delta[i])
    
print('Weights : ' + str(weights))
print('Weight Deltas : ' + str(weights_delta))

Weights : [0.3, 0.20177178421875, 0.90327098625]
Weight Deltas : [0, -0.017717842187500006, -0.032709862500000006]


Чистая сеть с несколькими входами и выходами

In [340]:
weights = [
    [0.1, 0.1, -0.3], 
    [0.1, 0.2, 0.1],
    [0.0, 1.3, 0.1]
]
def w_sum(a, b):
    
    assert(len(a) == len(b))
    
    output = 0
    
    for i in range(len(a)):
        output += (a[i] * b[i])
        
    return output

def vec_mat_mul(vect, matrix):
    
    assert(len(vect) == len(matrix))
    
    output = [0, 0, 0]
    
    for i in range(len(vect)):
        output[i] = w_sum(vect, matrix[i])
        
    return output

def neural_network(input, weights):
    
    pred = vec_mat_mul(input, weights)
    
    return pred

In [341]:
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

hurt = [0.1, 0.0, 0.0, 0.1]
win = [1, 1, 0, 1]
sad = [0.1, 0.0, 0.1, 0.2]

alpha = 0.01

input = [toes[0], wlrec[0], nfans[0]]

true = [hurt[0], win[0], sad[0]]

In [342]:
pred = neural_network(input, weights)

error = [0, 0, 0]
delta = [0, 0, 0]

for i in range(len(delta)):
    
    error[i] = (pred[i] - true[i]) ** 2
    delta[i] = pred[i] - true[i]

In [343]:
def outer_prod(vec_a, vec_b):
    
    out = np.zeros((len(vec_a), len(vec_b)))
    
    for i in range(len(vec_a)):
        for j in range(len(vec_b)):
            out[i][j] = vec_a[i] * vec_b[j]
    
    return out

In [344]:
input = [toes[0], wlrec[0], nfans[0]]
true = [hurt[0], win[0], sad[0]]

In [345]:
pred = neural_network(input, weights)

error = [0, 0, 0]
delta = [0, 0, 0]

for i in range(len(true)):
    
    error[i] = (pred[i] - true[i]) ** 2
    delta[i] = pred[i] - true[i]

In [346]:
a = np.array(input)
a

array([8.5 , 0.65, 1.2 ])

In [347]:
b = np.array(delta)
b

array([0.455, 0.1  , 0.865])

In [348]:
np.outer(a, b)

array([[3.8675 , 0.85   , 7.3525 ],
       [0.29575, 0.065  , 0.56225],
       [0.546  , 0.12   , 1.038  ]])

In [561]:
weights_delta = outer_prod(input, delta)
weights_delta

array([[3.8675 , 0.85   , 7.3525 ],
       [0.29575, 0.065  , 0.56225],
       [0.546  , 0.12   , 1.038  ]])